package tests.inventory;
import org.testng.annotations.*;
import org.openqa.selenium.By;
import configuration.Inv_testConfig;
import java.io.IOException;

public class CreateInventoryTest implements Inv_testConfig {

    @Test
    public void createNewInventory() throws InterruptedException, IOException {
        appInv.clickOnTheCreateNewInventoryButton();
        appInv.type(By.id("inventory_name"),"Connor");
        appInv.type(By.id("inventory_id"), "2189-1-1");
        appInv.hideKeyboard();
        appInv.clickOnTheCreateButton();
        appInv.clickOnTheEditInventoryButton();
        appInv.clickOnTheAddPieceButton();
        appInv.selectLocationForTheNewPiece();
        appInv.selectPackageForNewPiece();
        appInv.selectPBOForNewPiece();
        appInv.addItemIntoNewPiece();
        appInv.showParametersOfTheItem();
        appInv.changeConditionOfNewItem();
        appInv.changeTypeOfNewItem();
        appInv.addConditionToTheNewItem();
        appInv.hideKeyboard();
        appInv.addLocationToTheNewItem();
        appInv.hideKeyboard();
        appInv.attachPhotoToTheNewItem();
        appInv.clickToTheReturnUpButton();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheRoomsButtonOnTheInventoryScreen();
        appInv.selectRoomWithItem();
        appInv.clickOnTheShowRoomButtonOnTheRoomsScreen();
        appInv.fillDescriptionField();
        appInv.hideKeyboard();
        appInv.fillConditionField();
        appInv.hideKeyboard();
        appInv.attachPhotoToThePropertyForPacking();
        appInv.selectPropertyBeforePacking();
        appInv.clickOnTheSelectConditionButtonOfPropertyBeforePacking();
        appInv.clickOnPropertyConditionsButtonBeforePacking();
        appInv.attachPhotoToThePropertyForPacking();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnPropertyConditionsFieldAfterPacking();
        appInv.attachPhotoToThePropertyForPacking();
        appInv.selectPropertyAfterPacking();
        appInv.clickOnTheSelectConditionButtonOfPropertyAfterPacking();
        appInv.clickOnPropertyConditionsButtonAfterPacking();
        appInv.attachPhotoToThePropertyForPacking();
        appInv.clickToTheReturnUpButton();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheInventoryList();
        appInv.clickOnTheAppliances();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnThePackers();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnTheLoader();
        appInv.clickOnTheAddSkidButton();
        appInv.clickOnTheSelectSkidDropDown();
        appInv.attachPhotoToTheNewSkid();
        appInv.clickOnTheLoadSkidButton();
        appInv.clickToTheReturnUpButton();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnTheCartonsSummary();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnTheAdditionalMaterials();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnTheServices();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnTheAdditionalInfo();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheAdditionalListButton();
        appInv.clickOnTheDocuments();
        appInv.clickOnTheAddDocumentButton();
        appInv.fillDocumentNameField();
        appInv.hideKeyboard();
        appInv.attachPhotoToTheDocumentSection();
        appInv.returnToTheDiscoveryPage();
        appInv.clickOnTheReportInventoryButton();
        appInv.swipeScreenDown();
        appInv.clickOnTheClientShipperButton();
        appInv.createSignatureInTheInventory();
        appInv.clickToTheReturnUpButton();
        appInv.clickOnTheForemanDriverButton();
        appInv.createSignatureInTheInventory();
        appInv.clickToTheReturnUpButton();
        appInv.swipeScreenUp();
        appInv.clickOnTheUploadButton();
        appInv.clickOnTheOKButtonOnThePopUp();
        appInv.screenshot();
        appInv.clickToTheReturnUpButton();
    }
}
